### ISSUE TITLE
ubuntu:xenial is deprecated

### ISSUE THREAD

**Issue by nrbnlulu** [pplonski/simple-tasks#36]
this is the image you use for the django app

**Comment by pplonski** [comment]
thanks @nrbnlulu! this repository is for learning purposes, it is not used in production.

Are you able to fix the problem yourself?

**Comment by nrbnlulu** [comment]
Hehe working working on it, thanks for this repository! @pplonski 
would nice to be updated now and then though, if i would make it i can try to make a pr...
